---
apiVersion: v1
kind: Secret
metadata:
  name: psdi-organic-toolkit-sa-secret
  annotations:
    kubernetes.io/service-account.name: psdi-organic-toolkit-admin-sa
type: kubernetes.io/service-account-token
