---
apiVersion: v1
kind: Secret
metadata:
  name: organic-toolkit-hub-sa-secret
  annotations:
    kubernetes.io/service-account.name: organic-toolkit-hub-admin-sa
type: kubernetes.io/service-account-token
