---
apiVersion: v1
kind: Secret
metadata:
  name: PROJECT_NAME_HYPHEN-sa-secret
  annotations:
    kubernetes.io/service-account.name: PROJECT_NAME_HYPHEN-admin-sa
type: kubernetes.io/service-account-token
