# Workflow for continuous integration tasks triggered on non-draft pull requests to main and release

name: CI - PRs
run-name: CI - PRs
on:
  workflow_dispatch:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]
    branches: ["main", "release"]
    # No need to run tests for doc-only changes, maintenance code, or deployment code not covered by tests
    paths-ignore:
      - "**.md"
      - "Dockerfile"
      - "LICENSE"
      - "**.txt"
      - "deploy/**"
      - "scripts/fetch-common-style.*"

jobs:
  test-python:
    if: github.event.pull_request.draft == false
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/test-python.yml@c0f51fb2cbe8d5e6fcb495549c5eb0063b627558
    with:
      source_dir: psdi_organic_toolkit

  test-gui:
    if: github.event.pull_request.draft == false
    name: Run a simple test of the gui locally
    uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/test-gui.yml@c0f51fb2cbe8d5e6fcb495549c5eb0063b627558
    with:
      simple: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
